#!/usr/bin/env python3
"""Regenerate all-keys.yaml, which names every entity the component can produce.

Run with --check in CI: a key added to settings.py without regenerating fails the build
rather than going quietly untested.
"""

import argparse
import importlib
import importlib.machinery
import importlib.util
import pathlib
import sys

HERE = pathlib.Path(__file__).parent
# Imported as a package so the platforms' relative imports resolve; every entity list is
# read from source rather than restated here, or the check below would not see a new key.
sys.path.insert(0, str(HERE.parent))
sys.modules.setdefault("components", importlib.util.module_from_spec(
    importlib.machinery.ModuleSpec("components", None, is_package=True)
))
sys.modules["components"].__path__ = [str(HERE.parent / "components")]
hub = importlib.import_module("components.aecc")
settings = importlib.import_module("components.aecc.settings")
sensors = importlib.import_module("components.aecc.sensor")
binary_sensors = importlib.import_module("components.aecc.binary_sensor")

HEAD = """# Generated by tests/generate.py. Every entity the component can produce, so CI covers
# the keys example.yaml does not name.
esphome:
  name: aecc-all-keys

esp32:
  board: esp32dev
  framework:
    type: esp-idf

external_components:
  - source:
      type: local
      path: ../components

# backup: serves over HTTP, which needs a network.
wifi:
  ssid: test
  password: testtesttest

web_server:
  version: 3

uart:
  - id: bus_inverter
    tx_pin: GPIO32
    rx_pin: GPIO33
    baud_rate: 9600
  - id: bus_meter
    tx_pin: GPIO25
    rx_pin: GPIO26
    baud_rate: 9600

aecc:
  id: nova
  uart_id: bus_inverter
  backup:
    url: /aecc/backup
  datalogger:
    host: 192.0.2.10
    resting_power_number: Resting power
  meter:
    type: rs071
    uart_id: bus_meter
  control:
    mode_select: Battery mode
    setpoint_number: Battery power
"""

CONTROL_NUMBERS = tuple(hub.CONTROL_NUMBERS)
SENSORS = tuple(sensors.PRESETS) + tuple(sensors.DIAGNOSTICS)
BINARY_SENSORS = tuple(binary_sensors.HEALTH)


def render():
    title = lambda k: k.replace("_", " ")
    out = HEAD.splitlines()
    out += [f"    {k}_number: {title(k)}" for k in CONTROL_NUMBERS]
    out += [f"  {k}_number: {title(k)}" for k in settings.NUMBERS]
    out += [f"  {k}_switch: {title(k)}" for k in settings.SWITCHES]
    out += [f"  {k}_select: {title(k)}" for k in settings.SELECTS]
    out += [
        "  registers:",
        "    - name: Parallel mode",
        "      address: 0xA02C",
        "      max_value: 7",
        "    - name: Grid overvoltage trip",
        "      address: 0xA04D",
        "      scale: 0.1",
        "      max_value: 300",
        "",
        "sensor:",
        "  - platform: aecc",
    ]
    out += [f"    {k}:\n      name: {title(k)}" for k in SENSORS]
    out += ["", "binary_sensor:", "  - platform: aecc"]
    out += [f"    {k}:\n      name: {title(k)}" for k in BINARY_SENSORS]
    out += ["", "button:", "  - platform: aecc", "    backup:",
            "      name: Back up configuration", ""]
    return "\n".join(out)


parser = argparse.ArgumentParser()
parser.add_argument("--check", action="store_true")
args = parser.parse_args()

# The shape the mode select exists for: manual only, no meter and no second bus.
MANUAL_ONLY = """# Generated by tests/generate.py.
esphome:
  name: aecc-manual-only

esp32:
  board: esp32dev
  framework:
    type: esp-idf

external_components:
  - source:
      type: local
      path: ../components

uart:
  - id: bus_inverter
    tx_pin: GPIO32
    rx_pin: GPIO33
    baud_rate: 9600

aecc:
  id: nova
  uart_id: bus_inverter
  datalogger:
    host: 192.0.2.10
  control:
    setpoint_number: Battery power
"""

FILES = {"all-keys.yaml": render, "manual-only.yaml": lambda: MANUAL_ONLY}

stale = []
for name, build in FILES.items():
    target = HERE / name
    want = build()
    if not args.check:
        target.write_text(want)
        continue
    if not target.exists() or target.read_text() != want:
        stale.append(name)
if stale:
    sys.exit(f"{', '.join('tests/' + s for s in stale)} stale; run tests/generate.py")
