#!/usr/bin/env python3
"""Regenerate all-keys.yaml, which names every key the component accepts.

Run with --check in CI: a key the schema accepts but all-keys.yaml or the README does not
name fails the build, rather than going quietly untested or undocumented.
"""

import argparse
import importlib
import importlib.machinery
import importlib.util
import pathlib
import sys
import types

import voluptuous as vol
import yaml

HERE = pathlib.Path(__file__).parent
# Imported as a package so the platforms' relative imports resolve; every entity list is
# read from source rather than restated here, or the check below would not see a new key.
sys.path.insert(0, str(HERE.parent))
sys.modules.setdefault("components", importlib.util.module_from_spec(
    importlib.machinery.ModuleSpec("components", None, is_package=True)
))
sys.modules["components"].__path__ = [str(HERE.parent / "components")]
hub = importlib.import_module("components.aecc")
settings = importlib.import_module("components.aecc.settings")
telemetry = importlib.import_module("components.aecc.telemetry")
import esphome.config_validation as cv  # noqa: E402
from esphome.const import CONF_NAME  # noqa: E402

TIME_UNITS = {"days", "hours", "minutes", "seconds", "milliseconds", "microseconds"}


def schemas(v, depth=0):
    """Every schema reachable through a validator: All/Any, lists, closures, typed maps."""
    if depth > 8:
        return []
    if isinstance(v, vol.Schema):
        if isinstance(v.schema, dict):
            keys = {str(k) for k in v.schema}
            return [] if keys and keys <= TIME_UNITS else [v]
        return schemas(v.schema, depth + 1)
    if isinstance(v, (vol.All, vol.Any)):
        return [s for x in v.validators for s in schemas(x, depth + 1)]
    if isinstance(v, (list, tuple)):
        return [s for x in v for s in schemas(x, depth + 1)]
    if isinstance(v, dict):
        return [s for x in v.values() for s in schemas(x, depth + 1)]
    if isinstance(v, types.FunctionType) and v.__closure__:
        out = []
        for cell in v.__closure__:
            try:
                out += schemas(cell.cell_contents, depth + 1)
            except ValueError:
                pass
        return out
    return []


def walk(schema, path=(), out=None):
    """(path, is_entity, default) for every key, descending into blocks but not entities."""
    out = [] if out is None else out
    for key, value in schema.schema.items():
        if isinstance(key, cv.GenerateID) or str(key) == "setup_priority":
            continue
        subs = schemas(value)
        entity = bool(subs) and CONF_NAME in {str(k) for k in subs[0].schema}
        default = key.default() if isinstance(key, vol.Optional) and key.default is not vol.UNDEFINED else None
        out.append(("/".join(path + (str(key),)), entity, default))
        if not entity:
            for sub in subs:
                walk(sub, path + (str(key),), out)
    return out


KEYS = walk(schemas(hub.CONFIG_SCHEMA)[0])
# A typed schema's discriminator is checked by a function, not declared as a key.
KEYS.insert([p for p, _, _ in KEYS].index("meter") + 1, ("meter/type", False, None))
BLOCKS = {p.rsplit("/", 1)[0] for p, _, _ in KEYS if "/" in p}
# Values for the options whose default would not make a working configuration.
FIXED = {
    "uart_id": "bus_inverter",
    "expose_all_settings": "true",
    "meter/type": "rs071",
    "meter/uart_id": "bus_meter",
    "datalogger/host": "192.0.2.10",
}


def options(block):
    """The block's plain options as YAML lines, each at its default unless FIXED says."""
    prefix, indent = (f"{block}/", "    ") if block else ("", "  ")
    lines = []
    for path, entity, default in KEYS:
        leaf = path[len(prefix):]
        if entity or not path.startswith(prefix) or "/" in leaf or path in BLOCKS:
            continue
        value = FIXED.get(path, default)
        if value is None:
            sys.exit(f"{path} has no default; give it a value in FIXED")
        if isinstance(value, bool):
            value = str(value).lower()
        lines.append(f"{indent}{leaf}: {value}")
    return "\n".join(lines)


HEAD = """# Generated by tests/generate.py. Every key the component accepts, so CI covers the ones
# example.yaml does not name.
esphome:
  name: aecc-all-keys

esp32:
  board: esp32dev
  framework:
    type: esp-idf

external_components:
  - source:
      type: local
      path: ../components

# backup: serves over HTTP, which needs a network.
wifi:
  ssid: test
  password: testtesttest

web_server:
  version: 3

uart:
  - id: bus_inverter
    tx_pin: GPIO32
    rx_pin: GPIO33
    baud_rate: 9600
  - id: bus_meter
    tx_pin: GPIO25
    rx_pin: GPIO26
    baud_rate: 9600

aecc:
  id: nova
{top}
  backup:
{backup}
    button: Take a backup
  trace:
{trace}
    button: Take a trace
  work_mode_select: Work mode
  datalogger:
{datalogger}
    host_text: Battery address
    enable_switch: Datalogger link
    resting_power_number: Resting power
  meter:
{meter}
  control:
{control}
    mode_select: Battery mode
    setpoint_number: Battery power
    law_select: Control law
    rate_number: Loop rate
    filter_window_number: Filter window
    predictive_gain_number: Predictive gain
    meter_delay_number: Meter delay
"""

CONTROL_NUMBERS = tuple(hub.CONTROL_NUMBERS)


def render():
    title = lambda k: k.replace("_", " ")
    head = HEAD.format(top=options(""), **{b: options(b) for b in ("backup", "trace", "datalogger", "meter", "control")})
    out = head.splitlines()
    out += [f"    {k}_number: {title(k)}" for k in CONTROL_NUMBERS]
    out += [f"  {k}_number: {title(k)}" for k in settings.NUMBERS]
    out += [f"  {k}_switch: {title(k)}" for k in settings.SWITCHES]
    out += [f"  {k}_select: {title(k)}" for k in settings.SELECTS]
    # Named only to prove the relabel path; these are created without being named.
    for group in (telemetry.PRESETS, telemetry.DIAGNOSTICS, telemetry.HEALTH):
        out += [f"  {k}_sensor: {spec['name']}" for k, spec in group.items()]
    out += [
        "  registers:",
        "    - name: Parallel mode",
        "      address: 0xA02C",
        "      max_value: 7",
        "    - name: Grid overvoltage trip",
        "      address: 0xA04D",
        "      scale: 0.1",
        "      max_value: 300",
        "",
        "sensor:",
        "  - platform: aecc",
    ]
    out += ["    registers:", "      - name: Grid overvoltage trip",
            "        address: 0xA04D", "        scale: 0.1", "        interval: 60s"]
    out += [""]
    return "\n".join(out)


parser = argparse.ArgumentParser()
parser.add_argument("--check", action="store_true")
args = parser.parse_args()

# The shape the mode select exists for: manual only, no meter and no second bus.
MANUAL_ONLY = """# Generated by tests/generate.py.
esphome:
  name: aecc-manual-only

esp32:
  board: esp32dev
  framework:
    type: esp-idf

external_components:
  - source:
      type: local
      path: ../components

uart:
  - id: bus_inverter
    tx_pin: GPIO32
    rx_pin: GPIO33
    baud_rate: 9600

aecc:
  id: nova
  uart_id: bus_inverter
  expose_all_settings: true
  datalogger:
    host: 192.0.2.10
  control:
    setpoint_number: Battery power
"""

FILES = {"all-keys.yaml": render, "manual-only.yaml": lambda: MANUAL_ONLY}

def missing_keys(rendered):
    """Keys the schema accepts but all-keys.yaml never names."""
    aecc = yaml.safe_load(rendered)["aecc"]
    absent = []
    for path, _, _ in KEYS:
        node = aecc
        for part in path.split("/"):
            node = node.get(part) if isinstance(node, dict) else None
        if node is None:
            absent.append(path)
    return absent


def undocumented():
    """Keys the schema accepts but the README never mentions."""
    readme = (HERE.parent / "README.md").read_text()
    settings_keys = set(settings.NUMBERS) | set(settings.SWITCHES) | set(settings.SELECTS)

    def mentioned(key):
        # A block reads `meter:`; a battery setting is listed by name under its suffix.
        base = key.rsplit("_", 1)[0]
        names = (key, base) if base in settings_keys else (key,)
        return any(f"`{n}`" in readme or f"`{n}:`" in readme for n in names)

    return sorted({p.rsplit("/", 1)[-1] for p, _, _ in KEYS} - {
        p.rsplit("/", 1)[-1] for p, _, _ in KEYS if mentioned(p.rsplit("/", 1)[-1])})


stale = []
for name, build in FILES.items():
    target = HERE / name
    want = build()
    if not args.check:
        target.write_text(want)
        continue
    if not target.exists() or target.read_text() != want:
        stale.append(name)
if stale:
    sys.exit(f"{', '.join('tests/' + s for s in stale)} stale; run tests/generate.py")

absent = missing_keys(render())
if absent:
    sys.exit(f"all-keys.yaml names no {', '.join(absent)}; the README calls it exhaustive")
missing = undocumented()
if missing:
    sys.exit(f"README.md never mentions {', '.join(missing)}")
